# Generated by Django 2.2.4 on 2020-01-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200126_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='targeted_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Borrower'),
        ),
    ]
